deployment:
  tasks:
    - export DEPLOYPATH='/home4/sanasinvite.com/public_html/.dev132/wp-content/themes/sanas'
    - echo "Deploying to $DEPLOYPATH"
    - cd $DEPLOYPATH
    - git fetch --all
    - git reset --hard origin/main
    - echo "Deployment completed"
