deployment:
  tasks:
    - export DEPLOYPATH='/home4/sanasinvite.com/public_html/.dev132/wp-content/themes/sanas'
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - git pull https://github.com/parthwps/sanas.git
